# Server configuration
server.port=8080

# Algorithm choice: round-robin or random
lb.algorithm=round-robin

# Comma-separated list of backend servers
backend.servers=http://backend-1:7070,http://backend-2:7070,http://backend-3:7070,http://backend-4:7070,http://backend-6:7070
