# Server configuration
server.port=8080

# Algorithm choice: round-robin or random
lb.algorithm=round-robin

# Comma-separated list of backend servers
backend.servers=http://backend1:7070,http://backend2:7070,http://backend3:7070,http://backend4:7070,http://backend6:7070
